version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: fm_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: finance_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: